### PR TITLE
Add ES module

### LINKED ISSUE #46: module export for TypeScript
Hello,
first thank you for your wonderful library !

I am writing an app with TypeScript and importing it like :
`import { FuzzySet } from 'fuzzyset';`

but when instanciating,
`this._fuzzySet = FuzzySet();`

 I got this error : 
`ERROR TypeError: Object(...) is not a function`.

If I am correct, to allow your library to be TypeScript compatible, you can just update the final line to
`module.exports.FuzzySet = FuzzySet;`
(it may change the way to use it in vanilla JS)

Best regards !

### PR DESCRIPTION
**Pull request by jsejcksn**
This should resolve #46

### CODE REVIEW

**Comment by jsejcksn** [comment]
@Glench Thoughts?

**Comment by Glench** [comment]
I'm really not a big fan of having two of the same exact file. I don't know anything about Typescript — is there a way to make it work that works drop-in for the browser as well as in Typescript and Node?

**Comment by jsejcksn** [comment]
This this PR doesn't have anything to do with TypeScript—it's just a convenient side-effect that it solves #46.

> is there a way to make it work that works drop-in for the browser as well as in Typescript and Node?

## Short answer

If you want to support old browsers like IE11 and Node versions before [`12.17.0`](https://github.com/nodejs/node/releases/tag/v12.17.0), then you must provide separate files in formats supported by those environments.

Otherwise, you can drop the CommonJS file and just use ESM, in a **major** version change. If people want support for older formats, they can always use an older version of the package.

## More info

JavaScript [lacked an official, standardized module system until ES2015](https://hacks.mozilla.org/2018/03/es-modules-a-cartoon-deep-dive/), so Node chose to use [CommonJS](https://en.wikipedia.org/wiki/CommonJS). Now that ESM is the standard, Node supports it as well (without using any flags) starting in v[`12.17.0`](https://github.com/nodejs/node/releases/tag/v12.17.0). However, the decision to use an unofficial module system has made things complicated for the ecosystem. I encourage you to read about the complexities of [Node's transition to ESM](https://nodejs.org/api/esm.html), especially about [dual CJS/ESM packages](https://nodejs.org/api/esm.html#esm_dual_commonjs_es_module_packages).

If you want to publish multiple file formats, you can use a build step to generate them from your ESM source.

**Comment by Glench** [comment]
Thanks for your thorough response. I think for now I'm not going to merge this but if people are having issues then I'll look into it more.

**Comment by jordancue** [comment]
@Glench would urge you to strongly reconsider the decision not to include the library as an ES module as well. I tried a bunch of different configurations but aren't able to use fuzzyset with our build setup (TypeScript and rollup.js) without using @jsejcksn module directly. The file is similar but certainly not exactly the same, and exporting it as part of your build with a tool like rollup is trivial.

**Comment by Glench** [comment]
I don't know that I would ask anyone to strongly reconsider anything! The truth is I don't really know much about modules and these ecosystems but if there's interest I could look into it!

**Comment by jsejcksn** [comment]
@jordancue I'be been using https://github.com/krisk/Fuse. Take a look!

**Comment by Glench** [comment]
Alright, two complaints is enough for me! I restructured so that everything should be hunky dory now. Thank you all for your comments and help!

**Comment by jsejcksn** [comment]
@Glench I'm disappointed that you chose to close this PR, rejecting the effort I put into improving this project, and then you reused my work to effectively implement the same changes without recognizing my contribution.

**Comment by Glench** [comment]
@jsejcksn Oh! I definitely appreciate what you did and used it as an inspiration in implementing something that would work better for my own workflow and that's why I thanked you and @jordancue in my last comment. How else would you like your efforts acknowledged?

**Comment by jsejcksn** [comment]
@Glench 

[What is a contribution?](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-profile/viewing-contributions-on-your-profile?github-docs-dotcom-en%5Bquery%5D=contributor#what-counts-as-a-contribution)

[How to modify someone else's Github pull request?](https://stackoverflow.com/questions/44030176/how-to-modify-someone-elses-github-pull-request/45114109)

**Comment by Glench** [comment]
Hey, when you link to those pages I feel confused because I don't know what you're wanting from me and I'm wanting clarity so I can help meet your needs. So could you give me a direct request for what you're wanting?

**Comment by jsejcksn** [comment]
@Glench I don't have any specific "needs". Rather, I'm just trying to offer you insight about how not to drive away potential contributors.

It's discouraging for a person to put in work toward something, only to have their work rejected and then re-used as the basis for new work which duplicates their efforts. In this case, I think it would have been more appropriate for you to re-open this PR, edit it to your needs, and then merge it, which would indicate both your and my work in the commit history and contributor list.

**Comment by Glench** [comment]
So I'm hearing your request as acknowledging your disappointment and for me to think about the impact of closing pull requests on contributors. Happy to do both of those :)

**Pull request closed without merging**
